"""Keep complete native source models in Git, serve lossless GZIP at runtime.

Sites counts compressed runtime files toward its expanded-package size. Original
source bytes remain outside the dist-only deployment and are hash verified.
"""
from pathlib import Path
import gzip,hashlib,json,shutil
records=[]
keys=['vctclassic','reconphantom']
for key in keys:
    root=Path('dist/assets/imported')/key;source=Path('source-assets')/key
    for folder in sorted(p for p in root.iterdir() if p.is_dir() and p.name!='sound'):
        raw=folder/'model.mdl';original=source/folder.name/'model.mdl'
        if raw.exists():
            original.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(raw,original)
        data=original.read_bytes();compressed=gzip.compress(data,compresslevel=9,mtime=0)
        assert gzip.decompress(compressed)==data
        runtime=folder/'model.mdl.gz';runtime.write_bytes(compressed)
        if raw.exists():raw.unlink()
        records.append(dict(variant=folder.name,original=str(original),runtime=str(runtime),rawSHA256=hashlib.sha256(data).hexdigest(),gzipSHA256=hashlib.sha256(compressed).hexdigest(),originalBytes=len(data),runtimeBytes=len(compressed)))
p=Path('dist/imported-catalog.js');s=p.read_text();prefix='// Generated by scripts/import-collection-packs.py\nexport const COLLECTION_IMPORTS='
d=json.loads(s[len(prefix):].strip().rstrip(';'));
for key in keys:d[key]['modelFile']='model.mdl.gz'
p.write_text(prefix+json.dumps(d,ensure_ascii=False,indent=2)+';\n')
p=Path('docs/collection-import-sources.json');d=json.loads(p.read_text());d['runtimeCompression']=records
for r in records:
    for f in d['files']:
        if f['output']==r['runtime'][:-3]:f['output']=r['original'];f['runtimeOutput']=r['runtime']
p.write_text(json.dumps(d,ensure_ascii=False,indent=2))
print('Original native bytes',sum(r['originalBytes'] for r in records),'runtime GZIP bytes',sum(r['runtimeBytes'] for r in records),'lossless variants',len(records))
